version: "3.7"
services:
  app:
    build: ./model_api
    container_name: crypto-rest
    ports: 
      - "5000:5000"
  consumer:
    build: ./model_kafka
    container_name: crypto-consumer
    ports: 
      - "8000:8000"
    depends_on: 
        - "app"
